import json

from instagrapi.types import Media
from typing import List

from crawler.location.Location import Location


class CrawledData:

    def __init__(self, username, post_id, date, img_url: List[str], caption_text: str,
                 location: Location = None) -> None:
        self.__username = username
        self.__post_id = post_id
        self.__date = date
        self.__img_url = img_url
        self.__caption_text = caption_text
        self.__location = location
        self.__s3_id = []

    # getters
    def get_username(self) -> str:
        """
        Get the username of the user who posted the media.
        """
        return self.__username

    def get_post_id(self) -> str:
        """
        Get the post id of the media generated by instagrapi.
        """
        return self.__post_id

    def get_date(self) -> str:
        """
        Get the date when the media was posted.
        """
        return str(self.__date)

    def get_img_url(self) -> List[str]:
        """
        Get the urls of the images of the media.
        """
        return self.__img_url

    def get_caption_text(self) -> str:
        """
        Get the caption text of the media.
        """
        return self.__caption_text

    def get_location(self) -> Location:
        """
        Get an object of type Location which contains the location of the media.
        """
        return self.__location

    def get_s3_id(self) -> List[str]:
        """
        Get the id of the media in s3 wich corresponds to the id of the media in the database.
        """
        return self.__s3_id

    def get_id_location(self) -> int:
        """
        Get the id of the location of the media.
        """
        return self.__location.get_db_id()

    # setters
    def set_username(self, username: str) -> None:
        """
        Set the username of the user who posted the media.
        """
        self.__username = username

    def add_s3_id(self, s3_id: str) -> None:
        """
        Add the s3 id of the media to the list of s3 ids.
        """
        self.__s3_id.append(s3_id)

    def to_json(self) -> str:
        """
        Convert the object to a json string and return it.
        """
        json_obj = {
            "username": self.__username,
            "post_id": self.__post_id,
            "date": str(self.__date),
            "img_url": self.__s3_id,
            "caption_text": self.__caption_text,
            "location": self.__location.to_dict() if self.__location is not None else None
        }
        return json.dumps(json_obj)


